### ISSUE TITLE
录屏软件是啥啊

### ISSUE THREAD

**Issue by Tukali** [Ryan-the-hito/Olive#1]
大佬你用的录屏软件是啥啊，真好看

**Comment by Ryan-the-hito** [comment]
您好！

抱歉刚刚看到这封邮件！最近一周都在忙学校的事情，刚刚放假有空来看看嘿嘿~

您问到的这个录屏软件，我看了下，当时用的应该是这个：Any RecScreen。它还是个付费软件，但是我记得这个软件时不时会限免的，所以可以关注一下，像极微讯这样的微信公众号会定期发布一些限免软件的信息，等限免的时候下载比较实惠~

多谢关注和支持！🙏

Ryan-the-hito

[CleanShot 2023-09-30 at ***@***.***
------- Original Message -------

**Comment by Tukali** [comment]
好的，谢谢大佬，嘻嘻

**Comment by bsoprojects** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
